Enable support for exporting 1D and 2D dataset slices.
silx-kit/vscode-h5web pull request #23
Opened 2023-04-02 19:35 UTC by mandrew9

I'm admittedly not an expert with TypeScript or VS Code extensions, but I think this implementation for exporting data slices within the VS Code extension follows your guidelines provided in the associated ticket. Please let me know if there's anything I can do to improve the implementation.

2023-04-04 12:25 UTC, axelboc requested changes
Thanks for having a crack at this @mandrew9!

2023-04-04 12:25 UTC, axelboc commented on app/Viewer.tsx
> +              const finalCsv = csv.slice(0, -1);
With my suggestion above, I believe `-1` would have to be replaced with `-2` to remove both the last line break and last coma.

2023-07-09 19:26 UTC, mandrew9 commented on app/Viewer.tsx
> +                  if (subsets[i] === ':' && dataset.shape[i] > 1) {
Sorry it took me much longer to get back to this than I expected. Regarding this issue with transposition of the data, I think the problem is more complex. Based on the testing that I did, the user may transpose the data in the UI, but those changes are not reflected in the data about dimensionality sent to this function. Do you know if there is a means available to recover the dimensionality of the data as currently being viewed within the UI?

2023-07-17 13:14 UTC, axelboc commented on app/Viewer.tsx
> +                  if (subsets[i] === ':' && dataset.shape[i] > 1) {
Hmm, indeed you're right! I'll get back to you on this.

2023-07-26 06:59 UTC, axelboc commented on app/Viewer.tsx
> +                  if (subsets[i] === ':' && dataset.shape[i] > 1) {
Alright, I've opened an issue on the main H5Web repo: https://github.com/silx-kit/h5web/issues/1454 -- but it's not a blocking issue. Let's accept potential transpositions in the export for now.

2023-09-07 06:54 UTC, axelboc commented on app/App.tsx
> +  const [vscode, setVsCodeApi] = useState<VsCodeApi>();
In #29, I moved the `acquireVsCodeApi` call to a dedicated file – no need for a `useEffect` at all in the end.

2023-09-07 06:55 UTC, axelboc commented on app/Viewer.tsx
> +          if (format === 'csv') {
No longer relevant now that we also have the JSON export.

2023-09-07 08:08 UTC, axelboc commented
I've refactored the CSV export logic a bit to avoid filtering out dimensions with cardinality of 1 and to avoid having a specific `for` loop for 1D datasets/slices. I've also removed the extra space that was added after every comma.

Thanks again @mandrew9!

2023-09-07 08:09 UTC, axelboc approved these changes

2023-09-07 08:09 UTC, merged